environment:
  CYG_ROOT: C:\cygwin
  CYG_BASH: C:\cygwin\bin\bash
  CYG_CACHE: C:\cygwin\var\cache\setup
  CYG_EXE: C:\cygwin\setup-x86.exe
  CYG_MIRROR: http://cygwin.mirror.constant.com
  SCI_RUN: /cygdrive/c/smalltalkCI-master/run.sh
  MOSQUITTO_DIR: C:\mosquitto\
  matrix:
    - SMALLTALK: Pharo-5.0
    - SMALLTALK: Pharo-6.0

platform:
  - x86

install:
  - '%CYG_EXE% -qnNdO -R "%CYG_ROOT%" -s "%CYG_MIRROR%" -l "%CYG_CACHE%" -P unzip'
  - ps: Start-FileDownload "https://github.com/hpi-swa/smalltalkCI/archive/master.zip" "C:\smalltalkCI.zip"
  - 7z x C:\smalltalkCI.zip -oC:\ -y > NULL
  # mosquitto dependences
  - ps: Start-FileDownload "http://slproweb.com/download/Win32OpenSSL_Light-1_1_0e.exe" "C:\win32OpenSSL.exe"
  - cmd: 'C:\win32OpenSSL.exe /VERYSILENT /SP- /LOG="C:\win32OpenSSL.log" /DIR="%MOSQUITTO_DIR%"
  - ps: Start-FileDownload "ftp://sourceware.org/pub/pthreads-win32/pthreads-w32-2-9-1-release.zip" "C:\pthreads.zip"
  - 7z x C:\pthreads.zip -o%MOSQUITTO_DIR% -y > NULL
  # install mosquitto
  - ps: Start-FileDownload "http://www.eclipse.org/downloads/download.php?file=/mosquitto/binary/win32/mosquitto-1.4.11-install-win32.exe&mirror_id=1" "C:\mosquitto-win32.exe"
  - cmd: 'C:\mosquitto-win32.exe /S /D=%MOSQUITTO_DIR%'
  - cmd: 'dir %%MOSQUITTO_DIR%%'
  - ps: Get-Content -Path C:\mosquitto\readme-windows.txt

build: false

test_script:
  - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; $SCI_RUN"'
