language: smalltalk
sudo: true

os:
  - linux
  - osx

smalltalk:
  - Pharo-6.0
  - Pharo-5.0

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y mosquitto mosquitto-clients ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mosquitto ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew services start mosquitto ; fi
  - mosquitto_pub -h localhost -p 1883 -t abc -m 'checking mosquitto connection'
